version: "2.2"

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_CACHE_AND_QUEUE_DRIVER=cubestore
      - CUBEJS_PRE_AGGREGATIONS_SCHEMA=${CUBEJS_PRE_AGGREGATIONS_SCHEMA}
      - CUBEJS_DB_TYPE=${CUBEJS_DB_TYPE}
      - CUBEJS_DB_HOST=${CUBEJS_DB_HOST}
      - CUBEJS_DB_PORT=${CUBEJS_DB_PORT}
      - CUBEJS_DB_NAME=${CUBEJS_DB_NAME}
      - CUBEJS_DB_USER=${CUBEJS_DB_USER}
      - CUBEJS_DB_PASS=${CUBEJS_DB_PASS}
      - CUBEJS_DB_SSL=${CUBEJS_DB_SSL}
      - CUBEJS_PRE_AGG_ISSUE_TABLE_NAME=${CUBEJS_PRE_AGG_ISSUE_TABLE_NAME}
    volumes:
      - .:/cube/conf
